ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/dispsys/
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/smi/
ccflags-y += -I$(MTK_PATH_SOURCE)/../hardware/dpframework/inc/

obj-y += m4u.o m4u_kernel.o m4u_priv.o
obj-y += m4u_slt.o
